name: Cut Release (HACS)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (ex: 1.3.6 ou v1.3.6)"
        required: true
      prerelease:
        description: "Marquer comme pré-release ?"
        type: boolean
        default: false
      draft:
        description: "Créer en brouillon ?"
        type: boolean
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # nécessaire pour pousser sur main et créer tag
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Normaliser la version
        id: v
        shell: bash
        run: |
          v="${{ github.event.inputs.version }}"
          v="${v#v}"                    # retire le 'v' éventuel
          echo "clean=$v" >> $GITHUB_OUTPUT
          echo "tag=v$v" >> $GITHUB_OUTPUT

      - name: Mettre à jour manifest.json (main)
        shell: bash
        run: |
          file="custom_components/new_bestway_spa/manifest.json"
          tmp=$(mktemp)
          jq --arg v "${{ steps.v.outputs.clean }}" '.version=$v' "$file" > "$tmp" && mv "$tmp" "$file"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "$file"
          git commit -m "chore(release): bump manifest to ${{ steps.v.outputs.clean }}"
          git push origin HEAD:main

      - name: Créer le tag sur ce commit
        shell: bash
        run: |
          git tag -a "${{ steps.v.outputs.tag }}" -m "Release ${{ steps.v.outputs.tag }}"
          git push origin "${{ steps.v.outputs.tag }}"

      - name: Construire le ZIP HACS
        shell: bash
        run: |
          cd custom_components/new_bestway_spa
          zip -r ../../New_bestway_spa.zip ./

      - name: Créer la release et téléverser l’asset
        uses: softprops/action-gh-release@v2.2.2
        with:
          tag_name: ${{ steps.v.outputs.tag }}
          name: ${{ steps.v.outputs.tag }}
          files: New_bestway_spa.zip
          draft: ${{ github.event.inputs.draft }}
          prerelease: ${{ github.event.inputs.prerelease }}
          generate_release_notes: true
